(()=>{
 const panel=document.createElement('section');panel.className='notice-compose admin-special-v34';
 panel.innerHTML='<h2>공지 · 채팅 · 앨범 관리</h2><div class="start-reset"><b>체험학습 시작 준비</b><p>기본 공지 1개만 남기고 채팅과 일반 앨범을 비웁니다. 학생 계정·XP·미션 제출물은 유지합니다.</p><button id="prepareTrip">시작 준비 초기화</button></div><button data-reset="notices">기본 공지 1개만 남기기</button><div id="manageNotices"></div><h3>채팅방</h3><button data-reset="chat">방 청소하기</button><label>상단 중요사항<textarea id="pinnedText" maxlength="500" placeholder="빈칸으로 저장하면 고정 해제됩니다."></textarea></label><button id="savePinned">중요사항 고정 저장</button><h3>일반 앨범</h3><button data-reset="album">사진·동영상 앨범 초기화</button><p>미션 제출물은 아래 미션 관리에서 확인합니다.</p><input id="teacherPhoto" type="file" accept="image/*,video/mp4,video/quicktime,video/webm"><input id="teacherCaption" maxlength="120" placeholder="사진·동영상 설명"><p>동영상은 3분 이내·150MB 이하입니다.</p><button id="uploadTeacherPhoto">사진·동영상 등록</button><div id="managePhotos"></div><button id="refreshManage">목록 새로고침</button><p id="manageStatus" role="status"></p>';
 document.getElementById('adminBox').append(panel);const status=panel.querySelector('#manageStatus');let job=null,uploading=false;
 async function api(data){const r=await fetch('/.netlify/functions/room-admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...data,teacherPin})}),d=await r.json();if(!r.ok)throw Error(d.error||'처리 실패');return d;}
 async function run(b,fn){b.disabled=true;try{await fn();status.textContent='처리 완료';await load();}catch(e){status.textContent=e.message;}finally{b.disabled=false;}}
 panel.querySelectorAll('[data-reset]').forEach(b=>b.onclick=()=>{if(uploading)return;if(confirm(b.textContent+' — 기록을 삭제할까요?'))run(b,()=>api({area:b.dataset.reset,action:'reset'}));});
 panel.querySelector('#prepareTrip').onclick=e=>{if(uploading||!confirm('기본 공지 1개만 남기고, 채팅·상단 고정글·일반 앨범의 사진과 동영상을 삭제할까요?'))return;run(e.target,async()=>{for(const area of ['notices','chat','album'])await api({area,action:'reset'});await api({area:'chat',action:'pin',text:''});panel.querySelector('#pinnedText').value='';});};
 panel.querySelector('#savePinned').onclick=e=>run(e.target,()=>api({area:'chat',action:'pin',text:panel.querySelector('#pinnedText').value}));
 async function load(){try{for(const [area,key,target] of [['notices','notices','manageNotices'],['album','items','managePhotos']]){
  const r=await fetch('/.netlify/functions/'+area,{cache:'no-store'});if(!r.ok)throw Error('목록 조회 실패');const data=await r.json(),box=panel.querySelector('#'+target);box.replaceChildren();for(const item of data[key]||[]){const row=document.createElement('div');row.className='manage-row';if(area==='album'){const media=document.createElement('div');media.className='manage-media';SJMedia.show(media,item.media||{kind:'photo',url:'/.netlify/functions/album?id='+item.id});row.append(media);}const label=document.createElement('span');label.textContent=item.title||item.caption||(item.kind==='video'?'동영상':'사진');const del=document.createElement('button');del.textContent='삭제';del.onclick=()=>{if(confirm('이 항목을 삭제할까요?'))run(del,()=>api({area,action:'delete',id:item.id}));};row.append(label,del);box.append(row);}
 }}catch(e){status.textContent=e.message;}}
 panel.querySelector('#refreshManage').onclick=load;
 panel.querySelector('#teacherPhoto').onchange=()=>{job=null;};
 panel.querySelector('#uploadTeacherPhoto').onclick=async e=>{if(uploading)return;const b=e.target,file=panel.querySelector('#teacherPhoto'),caption=panel.querySelector('#teacherCaption');uploading=true;b.disabled=file.disabled=caption.disabled=true;try{if(!job){status.textContent='파일 준비 중…';job=await SJMedia.createJob(file.files[0]);}await SJMedia.upload(job,{teacherPin,caption:caption.value,onProgress:n=>status.textContent=`업로드 ${n}% · 화면을 열어 두세요.`});job=null;file.value=caption.value='';status.textContent='등록 완료';await load();}catch(e){status.textContent=e.message;}finally{uploading=false;b.disabled=file.disabled=caption.disabled=false;b.textContent=job?'업로드 다시 시도':'사진·동영상 등록';}};
 new MutationObserver(()=>{if(!document.getElementById('adminBox').hidden){load();fetch('/.netlify/functions/chat').then(r=>r.json()).then(d=>panel.querySelector('#pinnedText').value=d.pinned||'').catch(()=>{});}}).observe(document.getElementById('adminBox'),{attributes:true,attributeFilter:['hidden']});
 window.addEventListener('beforeunload',e=>{if(uploading){e.preventDefault();e.returnValue='';}});
})();
