(async function(){
  const grid=document.getElementById('albumGrid'),fileInput=document.getElementById('albumFile'),pick=document.getElementById('albumPick'),upload=document.getElementById('albumUpload'),caption=document.getElementById('albumCaption'),preview=document.getElementById('albumPreview');
  const p=SJ.current(),st=SJ.load();let prepared=null,filename='';
  const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const studentName=id=>SJ.students.find(s=>s.id===id)?.name||'학생';
  function fmt(ts){const d=new Date(ts);return d.toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})}
  function resize(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{let w=img.naturalWidth,h=img.naturalHeight;const max=1280;if(Math.max(w,h)>max){const r=max/Math.max(w,h);w=Math.round(w*r);h=Math.round(h*r)}const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,w,h);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.78))};img.onerror=reject;img.src=url})}
  pick.onclick=()=>{if(!p||!st.authToken){alert('학생으로 로그인한 뒤 사진을 올릴 수 있어요.');return}fileInput.click()};
  fileInput.onchange=async()=>{const f=fileInput.files?.[0];if(!f)return;pick.disabled=true;pick.textContent='사진 준비 중…';try{prepared=await resize(f);filename=f.name;preview.hidden=false;preview.innerHTML=`<img src="${prepared}" alt="업로드 미리보기"><small>업로드할 사진 미리보기</small>`;upload.disabled=false}catch{alert('사진을 준비하지 못했습니다.')}finally{pick.disabled=false;pick.textContent='사진 다시 선택'}};
  upload.onclick=async()=>{if(!prepared||!p||!st.authToken)return;upload.disabled=true;upload.textContent='업로드 중…';try{const r=await fetch('/.netlify/functions/album',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({studentId:p.id,token:st.authToken,imageData:prepared,caption:caption.value.trim(),originalName:filename})});const d=await r.json();if(!r.ok)throw new Error(d.error||'업로드 실패');prepared=null;fileInput.value='';caption.value='';preview.hidden=true;upload.disabled=true;upload.textContent='업로드';pick.textContent='사진 선택';await load()}catch(e){alert(e.message);upload.disabled=false;upload.textContent='업로드'}};
  async function load(){grid.innerHTML='<div class="album-loading-v38">사진을 불러오는 중…</div>';try{const r=await fetch('/.netlify/functions/album',{cache:'no-store'}),d=await r.json();const items=d.items||[];if(!items.length){grid.innerHTML='<div class="album-empty-v38">아직 올라온 사진이 없어요.<br>첫 번째 사진의 주인공이 되어보세요! 📸</div>';return}grid.innerHTML=items.map(x=>`<article class="album-card-v38"><div class="album-photo-v38"><img src="/.netlify/functions/album?id=${encodeURIComponent(x.id)}" alt="${esc(studentName(x.studentId))} 학생이 올린 원정 사진" loading="lazy"><span class="album-rank-v38">#${x.rank} 등록</span></div><div class="album-meta-v38"><div><b>${esc(studentName(x.studentId))}</b><time>${fmt(x.uploadedAt)}</time></div><a href="/.netlify/functions/album?id=${encodeURIComponent(x.id)}&download=1" download>⬇️ 다운로드</a></div>${x.caption?`<p>${esc(x.caption)}</p>`:''}</article>`).join('')}catch{grid.innerHTML='<div class="album-empty-v38">앨범 서버에 연결하지 못했습니다.</div>'}}
  await load();setInterval(load,20000);
})();
