(()=>{
 const grid=document.getElementById('albumGrid'),file=document.getElementById('albumFile'),pick=document.getElementById('albumPick'),upload=document.getElementById('albumUpload'),caption=document.getElementById('albumCaption'),preview=document.getElementById('albumPreview'),status=document.getElementById('albumStatus');
 let folder=new URLSearchParams(location.search).get('folder')||'photos',job=null,busy=false;const tabs=document.querySelectorAll('[data-folder]'),name=id=>id==='teacher'?'선생님':SJ.students.find(s=>s.id===id)?.name||'학생';
 const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
 async function load(){tabs.forEach(b=>b.setAttribute('aria-selected',b.dataset.folder===folder));document.getElementById('albumUploadPanel').hidden=folder==='missions';grid.replaceChildren();try{
  const missions=folder==='missions',auth=SJMedia.credentials();const r=await fetch('/.netlify/functions/'+(missions?'field-missions':'album'),missions?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...auth,action:'submissions'})}:{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'목록 조회 실패');const items=missions?d.items:(d.items||[]).filter(x=>(x.kind==='video')===(folder==='videos'));
  if(!items.length){grid.textContent=missions?'아직 제출한 미션이 없습니다. 미션 탭에서 열린 활동을 확인해주세요.':'아직 업로드된 파일이 없습니다.';return;}
  for(const x of items){const card=document.createElement('article');card.className='album-item-v38'+(missions?' submission-card':'');const box=document.createElement('div');if(x.media)SJMedia.show(box,x.media);else if(missions&&x.hasPhoto){const r=await fetch('/.netlify/functions/field-missions',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...auth,action:'photo',id:x.id,team:x.team})}),d=await r.json();if(d.image)SJMedia.show(box,{kind:'photo',url:d.image});}else if(!missions)SJMedia.show(box,{kind:'photo',url:'/.netlify/functions/album?id='+x.id});card.append(box);
   if(missions){card.append(text('h3',x.title));const p=text('p',x.text);p.className='submission-text';card.append(p,text('p','참여: '+x.members.map(name).join(', ')+' · 각 +20 XP'));}else card.append(text('p',x.caption||''));card.append(text('small',(missions?x.place:name(x.studentId))+' · '+new Date(x.time||x.uploadedAt).toLocaleString('ko-KR')));grid.append(card);}
 }catch(e){grid.textContent=e.message;}}
 tabs.forEach(b=>b.onclick=()=>{if(busy)return;folder=b.dataset.folder;load();});pick.onclick=()=>{if(!SJ.current()||!SJ.load().authToken){status.textContent='학생 로그인 후 올릴 수 있습니다. 교사는 관리자 모드에서 등록해주세요.';return;}file.accept=folder==='videos'?'video/mp4,video/quicktime,video/webm':'image/*';file.click();};
 file.onchange=async()=>{if(!file.files[0])return;job=null;pick.disabled=true;upload.disabled=true;try{job=await SJMedia.createJob(file.files[0]);if(preview.dataset.url)URL.revokeObjectURL(preview.dataset.url);const url=URL.createObjectURL(job.prepared.blob);preview.dataset.url=url;preview.hidden=false;SJMedia.show(preview,{kind:job.prepared.kind,url});status.textContent='준비 완료. 업로드를 눌러주세요.';upload.disabled=false;}catch(e){status.textContent=e.message;}finally{pick.disabled=false;}};
 upload.onclick=async()=>{if(!job||busy)return;busy=true;pick.disabled=upload.disabled=caption.disabled=true;try{await SJMedia.upload(job,{caption:caption.value,onProgress:n=>status.textContent=`업로드 ${n}% · 화면을 열어 두세요.`});folder=job.prepared.kind==='video'?'videos':'photos';job=null;file.value=caption.value='';preview.hidden=true;status.textContent='업로드 완료! 일반 앨범에는 경험치가 지급되지 않습니다.';await load();}catch(e){status.textContent=e.message;}finally{busy=false;pick.disabled=caption.disabled=false;upload.disabled=!job;upload.textContent=job?'업로드 다시 시도':'업로드';}};
 window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});load();
})();
