(()=>{
const $=s=>document.querySelector(s),money=n=>Number(n).toLocaleString('ko-KR')+'원',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let pin='',items=[],filter='all';const drafts=new Map();
async function api(body){const r=await fetch('/.netlify/functions/expenses',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,teacherPin:pin}),cache:'no-store'});const d=await r.json();if(!r.ok){const e=Error(d.error||'연결을 확인해주세요.');e.current=d.current;throw e;}return d;}
function summary(){const done=items.filter(x=>x.done),total=items.reduce((s,x)=>s+x.amount,0),paid=done.reduce((s,x)=>s+x.amount,0);$('#summary').innerHTML=`<b>집행 완료 ${done.length} / ${items.length}건</b><p>전체 산출액 ${money(total)}</p><p>완료 항목 산출액 ${money(paid)}</p><p>미집행 항목 산출액 ${money(total-paid)}</p>`;}
function render(){summary();$('#list').innerHTML='';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===filter));for(const item of items.filter(x=>filter==='all'||(filter==='done'?x.done:!x.done))){const c=document.createElement('article');c.className='card'+(item.done?' done':'');c.innerHTML=`<small>${esc(item.category)} · 예산 출처: ${esc(item.fund)}</small><h2>${esc(item.title)}</h2><p class="amount">${money(item.amount)}</p><p><small>단가 ${esc(item.unit)}원 · 인원 ${esc(item.people||'원문 미기재')}</small></p>${item.note?`<p class="original">${esc(item.note)}</p>`:''}<div class="actions"><div><button class="toggle" aria-pressed="${item.done}">${item.done?'✓ 집행 완료':'○ 미집행'}</button><small>눌러서 변경</small></div><div><label class="memoLabel" for="memo-${item.id}">메모</label><textarea id="memo-${item.id}" maxlength="2000" placeholder="결제 시각, 결제 방법, 영수증, 잔금 등을 기록하세요."></textarea><button class="save">메모 저장</button></div></div><p class="status" role="status"></p>`;
const ta=c.querySelector('textarea'),status=c.querySelector('.status');ta.value=drafts.has(item.id)?drafts.get(item.id):item.memo;const stamp=()=>item.updatedAt?'최근 저장: '+new Date(item.updatedAt).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}):'아직 집행 기록이 없습니다.';status.textContent=drafts.has(item.id)?'저장하지 않은 메모가 있습니다.':stamp();ta.oninput=()=>{if(ta.value===item.memo)drafts.delete(item.id);else drafts.set(item.id,ta.value);status.textContent='메모를 작성한 뒤 저장해주세요.';};
async function update(change){c.querySelectorAll('button').forEach(b=>b.disabled=true);status.textContent='저장 중…';try{const d=await api({action:'update',id:item.id,revision:item.revision,...change});Object.assign(item,d.item);if(Object.hasOwn(change,'memo')&&ta.value===change.memo)drafts.delete(item.id);c.classList.toggle('done',item.done);const b=c.querySelector('.toggle');b.textContent=item.done?'✓ 집행 완료':'○ 미집행';b.setAttribute('aria-pressed',String(item.done));summary();status.textContent='✓ 서버에 저장했습니다. '+stamp()+(drafts.has(item.id)?' (작성 중인 메모는 별도로 저장해주세요.)':'');}catch(e){if(e.current)Object.assign(item,e.current);status.textContent=e.message+' 작성한 메모는 그대로 남아 있습니다.';}finally{c.querySelectorAll('button').forEach(b=>b.disabled=false);}}
c.querySelector('.toggle').onclick=()=>update({done:!item.done});c.querySelector('.save').onclick=()=>update({memo:ta.value});$('#list').appendChild(c);}}
async function load(){const d=await api({action:'list'});items=d.items;$('#login').hidden=true;$('#content').hidden=false;render();}
$('#openExpenses').onclick=async()=>{pin=$('#expensePin').value;$('#error').textContent='';$('#openExpenses').disabled=true;try{await load();$('#expensePin').value='';}catch(e){$('#error').textContent=e.message;}finally{$('#openExpenses').disabled=false;}};
$('#expensePin').onkeydown=e=>{if(e.key==='Enter')$('#openExpenses').click();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;render();});$('#reload').onclick=()=>load().catch(e=>alert(e.message));$('#logout').onclick=()=>{if(drafts.size&&!confirm('저장하지 않은 메모가 있습니다. 잠글까요?'))return;pin='';items=[];drafts.clear();$('#list').innerHTML='';$('#content').hidden=true;$('#login').hidden=false;};window.addEventListener('beforeunload',e=>{if(drafts.size){e.preventDefault();e.returnValue='';}});

const context=document.modelContext;
if(context?.registerTool){
  Promise.resolve(context.registerTool({name:'read_expenses',title:'집행 현황 보기',description:'교사 PIN으로 연 현장 집행내역의 항목별 상태와 금액을 확인합니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){if(!pin||!items.length)throw Error('교사 PIN으로 집행내역을 먼저 여세요.');return {items:items.map(({id,title,amount,done,memo,revision})=>({id,title,amount,done,memo,revision}))};}})).catch(()=>{});
  Promise.resolve(context.registerTool({name:'save_expense',title:'집행 여부·메모 저장',description:'화면에 열린 집행 항목의 완료 여부 또는 메모를 서버에 저장하고 화면을 갱신합니다.',inputSchema:{type:'object',properties:{id:{type:'string'},done:{type:'boolean'},memo:{type:'string',maxLength:2000}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){
    if(!pin||!items.length)throw Error('교사 PIN으로 집행내역을 먼저 여세요.');
    if(!input||typeof input.id!=='string'||(!Object.hasOwn(input,'done')&&!Object.hasOwn(input,'memo'))||Object.hasOwn(input,'done')&&typeof input.done!=='boolean'||Object.hasOwn(input,'memo')&&(typeof input.memo!=='string'||input.memo.length>2000))throw Error('항목과 변경할 값을 확인해주세요.');
    const item=items.find(x=>x.id===input.id);if(!item)throw Error('해당 항목을 찾지 못했습니다.');
    const changes={};if(Object.hasOwn(input,'done'))changes.done=input.done;if(Object.hasOwn(input,'memo'))changes.memo=input.memo;
    const response=await api({action:'update',id:item.id,revision:item.revision,...changes});Object.assign(item,response.item);drafts.delete(item.id);render();return {id:item.id,done:item.done,memo:item.memo,revision:item.revision};
  }})).catch(()=>{});
}
})();