(function(){
 let tab=new URLSearchParams(location.search).get('island')==='dokdo'?'dokdo':'ulleung',idx=0,items=[],sequence=0;
 const stage=document.getElementById('quizStage'),lock=document.getElementById('quizLock'),score=document.querySelector('.quiz-score-v37');
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function api(body){const s=SJ.load(),data={studentId:s.studentId,token:s.authToken,island:tab,...body};const r=await fetch('/.netlify/functions/quiz'+(body?'':'?'+new URLSearchParams(data)),body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)}:{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'연결을 확인해주세요.');return d;}
 function render(){const q=items[idx];if(!q)return;const a=q.attempt;document.getElementById('quizSolved').textContent=items.filter(x=>x.attempt).length+' / 5 제출';document.getElementById('quizXp').textContent=(items.filter(x=>x.attempt?.correct).length*10)+' / 50 XP';
 stage.innerHTML=`<article class="quiz-card-v37"><div class="quiz-progress-v37"><span>${tab==='ulleung'?'울릉도':'독도'} ${idx+1} / 5</span><i>${a?(a.correct?'정답 · +10 XP':'오답 · 0 XP'):'첫 답안만 인정 · 정답 +10 XP'}</i></div><h2>${esc(q.q)}</h2><div class="quiz-choices-v37">${q.choices.map((c,i)=>`<button type="button" data-i="${i}" ${a?'disabled':''} class="${a&&i===a.choice?(a.correct?'correct':'wrong'):''}"><b>${i+1}</b>${esc(c)}${a&&i===a.choice?' ✓ 선택':''}</button>`).join('')}</div><div id="quizFeedback" class="quiz-feedback-v37" ${a?'':'hidden'}>${a?`${a.correct?'정답입니다!':'오답으로 기록되었습니다.'} 정답: ${esc(q.choices[a.answer])}<br>${esc(a.why)}${a.legacy?'<br>이전 버전에서 받은 보상 기록입니다.':''}`:''}</div><div class="quiz-next-v37"><button id="quizPrev" ${idx===0?'disabled':''}>← 이전</button><button id="quizNext">${idx===4?'처음으로':'다음 →'}</button></div></article><p>답안을 누르면 바로 확정됩니다. 오답도 다시 선택할 수 없어요.</p>`;
 stage.querySelectorAll('[data-i]').forEach(btn=>btn.onclick=async()=>{const choice=Number(btn.dataset.i);stage.querySelectorAll('button').forEach(b=>b.disabled=true);document.querySelectorAll('.quiz-tabs-v37 button').forEach(b=>b.disabled=true);try{const d=await api({id:q.id,choice});q.attempt=d.attempt;SJ.save({...SJ.load(),...d.progress});render();}catch(e){const fb=document.getElementById('quizFeedback');fb.hidden=false;fb.textContent=e.message;const retry=document.createElement('button');retry.textContent='저장된 답안 확인하기';retry.onclick=load;fb.appendChild(retry);}finally{document.querySelectorAll('.quiz-tabs-v37 button').forEach(b=>b.disabled=false)}});
 document.getElementById('quizPrev').onclick=()=>{idx--;render()};document.getElementById('quizNext').onclick=()=>{idx=(idx+1)%5;render()};
 }
 async function load(){const ticket=++sequence;stage.hidden=true;score.hidden=true;lock.hidden=false;lock.querySelector('h2').textContent='퀴즈 확인 중…';document.querySelectorAll('.quiz-tabs-v37 button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));try{const d=await api();if(ticket!==sequence)return;items=d.items;idx=0;lock.hidden=true;stage.hidden=false;score.hidden=false;render()}catch(e){if(ticket===sequence)lock.querySelector('h2').textContent=e.message;}}
 document.querySelectorAll('.quiz-tabs-v37 button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;load()});load();
})();
