const loginBox=document.querySelector('#loginBox'),adminBox=document.querySelector('#adminBox'),pin=document.querySelector('#pin');let teacherPin='',gateState=null,draftGroups=null;
async function specialRequest(body){const r=await fetch('/.netlify/functions/special-mission',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...body,teacherPin}),cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'돌발 안내 서버 연결 실패');return d}
async function loadSpecial(){try{const r=await fetch('/.netlify/functions/special-mission',{cache:'no-store'});const d=await r.json();const el=document.querySelector('#currentSpecial');if(d.mission)el.innerHTML=`<b>현재 미션</b><span>${String(d.mission.text).replace(/[<>]/g,'')}</span>`;else el.textContent='현재 돌발 안내이 없습니다.'}catch{}}
async function loadGates(){try{const r=await fetch('/.netlify/functions/feature-gates',{cache:'no-store'}),d=await r.json();gateState=d.state;drawGates()}catch{}}
const learningGates={history_ulleung:'📖 울릉도 이야기 3개',quiz_ulleung:'⛴️ 울릉도 퀴즈 10문제',history_dokdo:'📖 독도 이야기 3개',quiz_dokdo:'🇰🇷 독도 퀴즈 10문제'};
function drawGates(){const grid=document.querySelector('.gate-grid-v38');grid.innerHTML=Object.entries(learningGates).map(([k,n])=>`<div><b>${n}</b><small>${gateState?.[k]?.open?'현재 공개 중':'현재 잠김'}</small><button data-gate="${k}">${gateState?.[k]?.open?'🔒 닫기':'🔓 열기'}</button></div>`).join('');grid.querySelectorAll('[data-gate]').forEach(b=>b.onclick=()=>toggleGate(b.dataset.gate,b));}
async function toggleGate(k,b){b.disabled=true;try{const r=await fetch('/.netlify/functions/feature-gates',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({teacherPin,feature:k,open:!gateState?.[k]?.open})}),d=await r.json();if(!r.ok)throw Error(d.error||'변경 실패');gateState=d.state;drawGates()}catch(e){alert(e.message);b.disabled=false}}

function renderAttendance(){const box=document.querySelector('#attendanceGrid');box.innerHTML=SJ.students.map(s=>`<label><input type="checkbox" value="${s.id}" checked><span><b>${s.name}</b><small>${s.grade}학년 · ${s.gender==='M'?'남':'여'}</small></span></label>`).join('')}
function shuffled(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function groupScore(groups,all){const total=all.length,grades=[1,2,3],genders=['M','F'];let score=0;for(const g of groups){for(const grade of grades){const totalC=all.filter(x=>x.grade===grade).length,actual=g.filter(x=>x.grade===grade).length,expected=totalC*g.length/total;score+=(actual-expected)**2*3}for(const sex of genders){const totalC=all.filter(x=>x.gender===sex).length,actual=g.filter(x=>x.gender===sex).length,expected=totalC*g.length/total;score+=(actual-expected)**2*2}}return score}
function makeBalanced(ids){const all=ids.map(id=>SJ.students.find(s=>s.id===id)).filter(Boolean);const n=all.length;if(n<6)throw new Error('조편성을 위해 참석 학생을 6명 이상 선택해주세요.');const base=Math.floor(n/3),rem=n%3,sizes=[base+(rem>0?1:0),base+(rem>1?1:0),base];let best=null,bestScore=1e9;for(let t=0;t<1200;t++){const a=shuffled(all),gs=[a.slice(0,sizes[0]),a.slice(sizes[0],sizes[0]+sizes[1]),a.slice(sizes[0]+sizes[1])],sc=groupScore(gs,all)+Math.random()*.01;if(sc<bestScore){bestScore=sc;best=gs}}return best.map((g,i)=>({name:`${i+1}조`,members:g.map(x=>x.id)}))}
function selectedIds(){return [...document.querySelectorAll('#attendanceGrid input:checked')].map(x=>x.value)}
function drawGroupPreview(){const box=document.querySelector('#groupPreview');if(!draftGroups){box.innerHTML='<p>자동 편성을 누르면 미리보기가 표시됩니다.</p>';return}box.innerHTML=draftGroups.map(g=>`<article><h3>${g.name} <span>${g.members.length}명</span></h3>${g.members.map(id=>{const s=SJ.students.find(x=>x.id===id);return `<div><b>${s.name}</b><small>${s.grade}학년 · ${s.gender==='M'?'남':'여'}</small></div>`}).join('')}</article>`).join('');document.querySelector('#publishGroups').disabled=false}
function generate(){try{draftGroups=makeBalanced(selectedIds());drawGroupPreview()}catch(e){alert(e.message)}}
async function groupStatus(){try{const r=await fetch('/.netlify/functions/groups',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error();document.querySelector('#groupAdminStatus').textContent=d.current?'현재 조편성이 확정되어 학생에게 보입니다.':'현재 조편성이 안 되었어요. 학생 화면에도 미편성으로 표시됩니다.'}catch{document.querySelector('#groupAdminStatus').textContent='조편성 상태를 확인하지 못했습니다.'}}
document.querySelector('#generateGroups').onclick=generate;document.querySelector('#rerollGroups').onclick=generate;document.querySelector('#publishGroups').onclick=async()=>{if(!draftGroups)return;if(!confirm('이 조편성을 확정하고 학생들에게 알릴까요?'))return;const b=document.querySelector('#publishGroups');b.disabled=true;b.textContent='확정 중…';try{const r=await fetch('/.netlify/functions/groups',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'publish',teacherPin,groups:draftGroups})}),d=await r.json();if(!r.ok)throw new Error(d.error||'조편성 저장 실패');await groupStatus();alert('조편성이 확정되었습니다. 학생들에게 공지와 팝업 알림이 전달됩니다.')}catch(e){alert(e.message)}finally{b.disabled=false;b.textContent='✅ 조편성 확정 및 알림'}};
document.querySelector('#resetGroups').onclick=async e=>{if(!confirm('현재 확정된 조편성을 초기화할까요? 학생 화면에는 “아직 조편성이 안 되었어요”가 표시됩니다. 미션 제출물과 XP는 유지됩니다.'))return;const b=e.currentTarget;b.disabled=true;try{const r=await fetch('/.netlify/functions/groups',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'reset',teacherPin}),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'초기화 실패');draftGroups=null;drawGroupPreview();document.querySelector('#publishGroups').disabled=true;await groupStatus()}catch(err){alert(err.message)}finally{b.disabled=false}};
async function loadXpRoster(){try{const r=await fetch('/.netlify/functions/student-progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'teacher-roster',teacherPin}),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'XP 조회 실패');document.querySelectorAll('#teacherXpRoster [data-student]').forEach(row=>{const s=SJ.students.find(x=>x.id===row.dataset.student);row.querySelector('.xp-current').textContent=`${s.grade}학년 · 현재 ${d.roster[s.id]} XP`})}catch(e){document.querySelectorAll('#teacherXpRoster .xp-current').forEach(x=>x.textContent=e.message)}}
function renderXpRoster(){const box=document.querySelector('#teacherXpRoster');box.innerHTML='';SJ.students.forEach(s=>{const row=document.createElement('div');row.className='teacher-password-row xp-row-v35';row.dataset.student=s.id;row.innerHTML=`<div><b>${s.name}</b><small class="xp-current">${s.grade}학년 · 조회 중…</small></div><div class="xp-stepper"><button type="button" data-step="-10" aria-label="${s.name} 조정값 10 XP 줄이기">−10</button><output aria-live="polite">0 XP</output><button type="button" data-step="10" aria-label="${s.name} 조정값 10 XP 늘리기">+10</button><button type="button" class="xp-apply" disabled>적용</button></div>`;let amount=0;const output=row.querySelector('output'),apply=row.querySelector('.xp-apply');row.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{amount=Math.max(-1000,Math.min(1000,amount+Number(b.dataset.step)));output.textContent=`${amount>0?'+':''}${amount} XP`;apply.disabled=amount===0});apply.onclick=async()=>{apply.disabled=true;row.querySelectorAll('[data-step]').forEach(b=>b.disabled=true);try{const r=await fetch('/.netlify/functions/student-progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'teacher-add-xp',studentId:s.id,amount,teacherPin,requestId:crypto.randomUUID()}),cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'XP 조정 실패');row.querySelector('.xp-current').textContent=`${s.grade}학년 · 현재 ${d.progress.xp} XP`;amount=0;output.textContent='0 XP'}catch(e){alert(e.message)}finally{row.querySelectorAll('[data-step]').forEach(b=>b.disabled=false);apply.disabled=amount===0}};box.appendChild(row)})}
function renderRoster(){const box=document.querySelector('#teacherRoster');box.innerHTML='';SJ.students.forEach(s=>{const row=document.createElement('div');row.className='teacher-password-row';row.innerHTML=`<div><b>${s.name}</b><small>${s.grade}학년 · ${s.gender==='M'?'남학생':'여학생'}</small></div><button type="button">비밀번호 초기화</button>`;row.querySelector('button').onclick=async()=>{if(!confirm(`${s.name} 학생의 비밀번호를 초기화할까요?`))return;const b=row.querySelector('button');b.disabled=true;try{await SJAuth.reset(s.id,teacherPin);alert(`${s.name} 학생 비밀번호가 초기화되었습니다.`);b.textContent='초기화 완료'}catch(e){alert(e.message);b.disabled=false}};box.appendChild(row)})}
function openAdmin(){loginBox.hidden=true;adminBox.hidden=false;renderAttendance();drawGroupPreview();renderXpRoster();renderRoster();loadXpRoster();groupStatus();loadSpecial();loadGates()}
document.querySelector('#login').onclick=async()=>{const v=pin.value.trim();if(!/^\d{4}$/.test(v)){alert('교사 PIN 4자리를 입력하세요.');return}const b=document.querySelector('#login');b.disabled=true;try{await SJAuth.teacherCheck(v);teacherPin=v;openAdmin()}catch(e){alert(e.message)}finally{b.disabled=false}};pin.addEventListener('keydown',e=>{if(e.key==='Enter')document.querySelector('#login').click()});
document.querySelector('#publishSpecial').onclick=async()=>{const text=document.querySelector('#specialText').value.trim();if(!text){alert('돌발 안내 내용을 입력해주세요.');return}const b=document.querySelector('#publishSpecial');b.disabled=true;try{await specialRequest({action:'publish',text});document.querySelector('#specialText').value='';await loadSpecial();alert('돌발 안내을 전송했습니다.')}catch(e){alert(e.message)}finally{b.disabled=false}};document.querySelector('#clearSpecial').onclick=async()=>{try{await specialRequest({action:'clear'});await loadSpecial()}catch(e){alert(e.message)}};
